---
 - hosts: localhost
   roles:
    - ansible-pacman
    - ansible-arch-keyserver
    - ansible-arch-xorg
    - ansible-kde-plasma
    - ansible-ssh
    - ansible-ssh-server
    - ansible-ufw
    - ansible-git
    - ansible-docker
    - ansible-arch-bluetooth-keyboard
    - ansible-hostname
